brimdata/react-arborist

- README.md
- package.json
- packages/demo/src/app.tsx
- packages/demo/src/got.tsx
- packages/react-arborist/package.json
- packages/react-arborist/src/components/tree.tsx
- packages/react-arborist/src/types.ts
The Tree component now has a `dndRootElement` prop that accepts null, undefined, or an HTML Node. If this prop exists, the drag and drop event handlers that are required by react-dnd will be scoped to that element. Any other native drag and drop listeners will work if they are not contained by the dndRootElement.
This fixes #17 
It should be noted, that the drag preview will only work when the mouse is contained within the dndRootElement. See this video for an example.
https://user-images.githubusercontent.com/3460638/170802194-7c137cad-c135-4ba7-8324-758f25587906.mp4
In this video, the dndRootElement is set to the parent of the <Tree> component. The \<h1\> element has a normal "draggable" attribute showing that other drag and drop behavior still works. However, see how the drag preview …
> Dnd Root Element Prop

- README.md
The example in the doc has a syntax error because of a missing comma. The PR adds that.
> fix (doc): add missing comma

- packages/react-arborist/src/types/tree-props.ts
When defining the width of my Tree I want to be able to take it 100% of the width. Now TypeScript will tell me only numbers are allowed even though strings work fine. ReactArborist uses FixedSizeList from react-window as seen here: https://github.com/brimdata/react-arborist/blob/fb7333811f167b8f695269668a16c55e82e86882/packages/react-arborist/src/components/default-container.tsx#L220 React-window docs tell us width can be a number or string: https://react-window.vercel.app/#/api/FixedSizeList
> Update width/height type to allow strings

- packages/react-arborist/src/data/create-root.ts
- packages/react-arborist/src/hooks/use-simple-tree.ts
- packages/react-arborist/src/types/tree-props.ts
This doesn't change anything about the implementation. It just changes the types to match the current reality a little bit more strictly.
> Small updates to the TypeScript types

- README.md
- packages/react-arborist/src/components/default-container.tsx
- packages/react-arborist/src/interfaces/node-api.ts
- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/types/tree-props.ts
Hey @jameskerr, thanks for your work on the library! 2.0 came out right before we had a use-case for it and it's been such a great foundation so far.
When following a master/detail pattern around the tree, I've found myself immediately relying on the focus state rather than the selection one to avoid multi-selected states (since they don't make sense in our use-case). What do you think of a prop to disable multi-selection?
> Feature: Single selection

- package.json
- packages/react-arborist/src/interfaces/tree-api.ts
* Change the script from `yarn dev` to `yarn start`.
* Remove a console.log when the tree can't find the current item to highlight/scroll to.
> Yarn Start Script

- packages/react-arborist/src/components/row-container.tsx
Closes #75 
The understanding is that RowContainer mounts/unmounts upon scrolling in and out of view since the list of nodes is virtualized. The RowContainer's useEffect for handling a focus event triggers on mount, causing the node to be focused and the scroll position to jump.
This change prevents scroll upon focusing which prevents the unintended jumping.
_NOTE: This solves the scroll bug, but without tests, I can't confidently say this hasn't introduced a regression. Would appreciate some help/guidance on testing_
> Prevent scrolling to nodes on scroll

- packages/react-arborist/src/components/default-container.tsx
Closes: https://github.com/brimdata/react-arborist/issues/85
This is a temporary fix to make focus search work for controlled trees without `onCreate` defined, before https://github.com/brimdata/react-arborist/pull/76 is implemented.
> Fix for when pressing the 'a' key and onCreate is not defined

- packages/showcase/styles/cities.module.css
Because the `globals.css` contains a media query setting the body text and background colors for `prefers-color-scheme: dark`, the tree on this demo becomes unreadable for "dark mode" users
(to test in chrome, dev tools, ctrl+shift+p > emulate dark)
before
after
> Fix the tree background color for the cities demo

- README.md
- packages/react-arborist/src/components/default-container.tsx
- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/types/tree-props.ts
Closes: https://github.com/brimdata/react-arborist/issues/83
This adds the prop `overscanCount` to the Tree where the user can change the number of nodes rendered but not visible
> Add prop to pass overscanCount to react-window

- packages/react-arborist/src/components/default-container.tsx
- packages/react-arborist/src/interfaces/node-api.ts
- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/types/tree-props.ts
- packages/showcase/data/gmail.ts
- packages/showcase/pages/gmail.tsx
> Disable edit

- packages/react-arborist/src/dnd/drop-hook.ts
- packages/react-arborist/src/types/tree-props.ts
This pull request is for the feature that allows users to disable the ability to drop a dragged item on a specific target at runtime.
> disabledDrop and target/source drop monitoring #62

- packages/react-arborist/src/components/provider.tsx
- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/state/selection-slice.ts
- packages/react-arborist/src/types/tree-props.ts
- packages/showcase/pages/gmail.tsx
Adds a new method to the `TreeApi` class called `setSelection`.
It allows for programatic control over the selection state. It is not concerned with changing focus or scrolling, only selection.
It accepts one argument. An object with the keys `{ids, anchor, mostRecent}`. These are the three pieces of state necessary for multiple selection.
Example:
```js
useEffect(() => {
tree.setSelection({
ids: ["1", "2", "3"],
anchor: "1", // or null
mostRecent: "3" // or null
})
}, [])
```
Fixes #156 #130 #145
> Add a treeApi.setSelection method.

- packages/react-arborist/src/dnd/compute-drop.ts
- packages/react-arborist/src/dnd/drag-hook.ts
- packages/react-arborist/src/dnd/drop-hook.ts
- packages/react-arborist/src/hooks/use-fresh-node.ts
- packages/react-arborist/src/interfaces/node-api.ts
- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/state/dnd-slice.ts
- packages/react-arborist/src/state/drag-slice.ts
- packages/react-arborist/src/state/initial.ts
- packages/react-arborist/src/utils.ts
- packages/showcase/next.config.js
- packages/showcase/pages/cities.tsx
- packages/showcase/pages/vscode.tsx
- packages/showcase/styles/vscode.module.css
- packages/showcase/tsconfig.json
Add the following methods to the tree api.
get dragNode() {
return this.get(this.state.nodes.drag.id);
}
get dragDestinationParent() {
return this.get(this.state.nodes.drag.destinationParentId);
}
get dragDestinationIndex() {
return this.state.nodes.drag.destinationIndex;
}
The demo is not finished yet, but these three new methods should unblock people from doing VSCode style dragging and dropping.
> Create a VSCode Demo

- packages/e2e/cypress/e2e/gmail-spec.cy.ts
- packages/react-arborist/src/components/default-container.tsx
- packages/react-arborist/src/components/row-container.tsx
This tree component has accessibility violations caught by Axe, and this PR addresses the violation for aria role and aria-level.
The row component has a role "treeitem", which requires a parent component with role "tree".
Also, aria-levels must be greater than or equal to 1, and since the root node starts at 0, this was causing another accessibility violation
Fixes #197
> Fix aria-level and aria role violations

- packages/react-arborist/src/interfaces/tree-api.ts
- packages/react-arborist/src/types/tree-props.ts
The tree doesn't mutate the children in the data, so the accessor can return a readonly array.
> Make children accessor readonly

- packages/showcase/pages/index.tsx
nextjs@14 change the `next/link` behavior, showcase indexpage will crash in nextjs@14
try to use `legacyBehavior` fix this problem
> fix: showcase indexpage crash in next@14

- modules/react-arborist/package.json
- modules/react-arborist/src/interfaces/tree-api.ts
- yarn.lock
- Fixes #271 
The behavior of 
```ts
return !utils.access(data, check);
```
and
```ts
return !utils.access(data, check) ?? true;
```
Is identical because `false ?? true === false` and `true ?? true === true`.
> build: Upgrade TypeScript, fix 5.6 error

- README.md
The readme, very strangely(!) does not include how to load react-arborist. VSCode intellisense is not able to locate where to get `<Tree>` from, at least when I tried it after a fresh install.
> Adding minimal required readme instructions

- modules/react-arborist/package.json
- yarn.lock
I noticed that when installing react-arborist in a react v19 project, pnpm complains that `react-window` does not support React 19. However, this was simply because the package.json of `react-window` did not have React v19 listed. They recently listed it and released a new version: https://github.com/bvaughn/react-window/pull/798. No changes were made from 1.8.10 to 1.8.11
> React 19 support: Bump react-window to 1.8.11

- modules/e2e/cypress/e2e/gmail-spec.cy.js
- modules/react-arborist/src/components/row-container.tsx
On our own project, we saw the need to add the attribute `aria-expanded` to the row elements, since it makes it easier to test with cypress.
This PR adds the attribute `aria-expanded` to the row container with the value `node.isOpen`.
Also updated the tests to verify the change.
> Add `aria-expanded` attribute to rows
